package view;

import javax.swing.table.DefaultTableModel;

public class Tabela extends javax.swing.JFrame {

    DefaultTableModel controle;
    int contador = 0;
    int colunaAtiva = 0;
    boolean trigger = false;

    public Tabela() {
        controle = new DefaultTableModel();
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePrincipal = new javax.swing.JTable();
        resultado1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePrincipal = new javax.swing.JTable(controle);
        tablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Xi", "Fi", "1º Ordem", "2º Ordem", "3º Ordem", "4º Ordem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePrincipal);
        if (tablePrincipal.getColumnModel().getColumnCount() > 0) {
            tablePrincipal.getColumnModel().getColumn(0).setMinWidth(25);
            tablePrincipal.getColumnModel().getColumn(0).setPreferredWidth(49);
            tablePrincipal.getColumnModel().getColumn(0).setMaxWidth(50);
            tablePrincipal.getColumnModel().getColumn(1).setPreferredWidth(49);
            tablePrincipal.getColumnModel().getColumn(1).setMaxWidth(50);
            tablePrincipal.getColumnModel().getColumn(2).setPreferredWidth(120);
            tablePrincipal.getColumnModel().getColumn(2).setMaxWidth(120);
            tablePrincipal.getColumnModel().getColumn(3).setPreferredWidth(120);
            tablePrincipal.getColumnModel().getColumn(3).setMaxWidth(120);
            tablePrincipal.getColumnModel().getColumn(4).setPreferredWidth(100);
            tablePrincipal.getColumnModel().getColumn(4).setMaxWidth(110);
        }

        resultado1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(resultado1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(resultado1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void incrementarColuna(double[] envio) { // to fix
        int temp = contador;
        for (int i = contador; i < envio.length; i++, temp += 2) {
            tablePrincipal.getModel().setValueAt(envio[i], temp, colunaAtiva);

        }
        if (trigger == false) {
            trigger = true;
        } else {

            contador++;
        }
        colunaAtiva++;

    }

    public void imprimirResultados(double r1) {
        resultado1.setText("Resultado: " + r1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultado1;
    private javax.swing.JTable tablePrincipal;
    // End of variables declaration//GEN-END:variables
}
